### ISSUE TITLE
Key Error after pyzotero v. 0.9.9.1

### ISSUE THREAD

**Issue by jmiba** [davidswelt/zot_bib_web#1]
zot.py throws a key error in all pyzotero versions after 0.9.9.1:

File "/volume1/homes/admin/Zotero/zot.py", line 395, in <module>
    collection_ids[coll[u'name']] = coll_key  #[x[u'key']]
KeyError: u'name'

**Comment by pdaengeli** [comment]
I can confirm this problem. `zot_bib_web` is working with `pyzotero` up to 0.9.9.1, but failing for more recent versions:

```
File "zot.py", line 343, in <module>
 collection_ids[coll[u'name']] = coll_key  #[x[u'key']]
 KeyError: u'name'
```

**Comment by davidswelt** [comment]
I have been testing this with Pyzotero 0.10.2, with no such problems.

I do get it with the latest version.  Jens, you wrote - "zot.py throws a key error in all pyzotero versions after 0.9.9.1” - can you confirm that 0.9.9.1 is the last working version for you?  

I’d like to find out what they’ve changed.

**Comment by pdaengeli** [comment]
Thanks for looking into this. I just tested it more thoroughly: versions 0.9.9, 0.9.9.1, 0.10, 0.10.1, and 0.10.2 are all working here, whereas versions 1.0.0, 1.0.1, 1.1.0, 1.1.1, and 1.1.2 are not working.

**Comment by davidswelt** [comment]
Thank you.  As a result of your bug report, two bugs were fixed.  A new pyzotero version is available (1.1.3) as of today, and I have just checked in a change that addresses a new limitation imposed by Zotero on its v3 API retrievals. Please let me know if the new versions work for you, so we can close this bug.

**Comment by pdaengeli** [comment]
Cool, thanks. I have only tested with a tiny test collection, but all goes smooth using [v.1.1.3](https://github.com/urschrei/pyzotero/releases/tag/v1.1.3) and commit a6d6ed4.

**Comment by davidswelt** [comment]
Zot_bib_web v1.1.0 is a new release with these fixes.
