### ISSUE TITLE
Handling of notes and attachements

### ISSUE THREAD

**Issue by jmiba** [davidswelt/zot_bib_web#2]
The most recent version of zot.py handles notes and attachments of collection items insufficiently rendering them as independent items. In the screenshot, there are two regular items, rendered as they should be, and three item attachements rendered as independent items.
![2015-03-23_1711](https://cloud.githubusercontent.com/assets/8625511/6784405/c684489e-d17f-11e4-9d99-02efd2f39eb2.png)

**Comment by davidswelt** [comment]
Thanks for your bug report.  Could you provide the collection ID used to produce your example case?

**Comment by jmiba** [comment]
Thanks for replying so soon. Well, in fact my example is from a closed membership group visible only for group members, but the problem is reproducible with any collection, be it user or group. You could try a collection from my publicly visible personal publication list (group id 55245), e.g. VUKBXBCJ, containing 13 bibliographic items, 10 of which have one or more attachements (PDFs, snapshots, or notes).

**Comment by davidswelt** [comment]
I trust the 21d80ff2 change (2015-03-25) took care of this, although I added the same filter to retrieve_atom.
