### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9'

### ISSUE THREAD

**Issue by Picaut** [davidswelt/zot_bib_web#5]
Your script seems very interesting and useful. However, I have an error when running it:

  File "xxxxxxxx\zot_bib_web\zot.py", line 579, in sortkeyname
    return SortAndValue(".".join([str(sortkeyname(field, value2).sort) for value2 in value]), sortkeyname(field, value[-1]).value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 43: ordinal not in range(128)

It may due to characters with accent in the name of the collection. Do you have a patch for this error?

**Comment by davidswelt** [comment]
Ok, could you please send me your settings file?

**Comment by Picaut** [comment]
OK, I send you the file by email.

**Comment by davidswelt** [comment]
Thank you for reporting this.  Please try the change I just pushed and let me know if it works for you.

**Comment by Picaut** [comment]
It seems good. Thank you very much for your very nice tool.

**Comment by davidswelt** [comment]
You’re welcome.  If you end up publishing the bibliography somewhere, would you mind sharing the link so I can include it as an example?
- David
