### ISSUE TITLE
Expandable lists or trees of tags for shortcuts

### ISSUE THREAD

**Issue by ashudeep** [davidswelt/zot_bib_web#8]
My Zotero tags look like "Parent tag>child tag", "Parent tag>child tag>grandchild tag" for different values of these parent, child and grandchild tag names. I want to make it look like an expandable list that only shows the parent tags in the beginning and then clicking [+] opens the list to child tags as well and another [+] click reveals all the tags in that tree.

**Comment by davidswelt** [comment]
That would be nice to have.  Perhaps a JS or Python-level API to include more arbitrary code at the top could do that.  Clients would provide a function that is called for each section, or that is called with a set of all tags, and then it can spit out code for these tags.  (The Zotero bibliography doesn't define a hierarchy of tags, does it?)

**Comment by TimBMK** [comment]
Is there any way (as of now) to do this for the sort_criteria? E.g., to expand and minimize collections in order to make it easier to navigate? 
Really great tool you made there, by the way!

**Comment by davidswelt** [comment]
There is no way to do it (sorry for late answer).  Ultimately, Zotero's format does not support this complication.  For hierarchical organization, folders are used.
