### ISSUE TITLE
doi

### ISSUE THREAD

**Issue by melTr** [davidswelt/zot_bib_web#9]
Hi
Just discover your program, thanks so much, fill my need!
Just have a suggestion/feature request. 
I would like to have doi in addition of link (or fallback). I circumvent this issue by using a style incorporating full doi address, ie http://doi.org/XXX. All styles with doi:XXX is not creating the link (it only writes the doi without a href). It works but I found it crowd my page with written link instead of a simple href.
Thanks to read!

**Comment by davidswelt** [comment]
That would be easy to do, actually.  Just add a link for any DOI.  Do you want to write a patch?

**Comment by davidswelt** [comment]
I committed such functionality.
